import Head from "next/head";

import { useDispatch, useSelector, useStore } from "react-redux";
import wrapper, { AppDispatch, RootState } from "redux_mango/store";
import { useCallback } from "react";
import { requestMessage } from "redux_mango/slice/helloSlice";

export default function Home() {
  const dispatch = useDispatch<AppDispatch>();
  const message = useSelector((state: RootState) => state.hello.message);
  const onRequest = useCallback(() => {
    dispatch(requestMessage());
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {message}
        <button onClick={onRequest}>누르기</button>
      </main>
    </>
  );
}
